# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

on:
  release:
    types:
      - released

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: NuGet
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore ./Cubido.Templates.csproj
      - name: Build
        run: dotnet build -c Release --no-restore ./Cubido.Templates.csproj
      - name: Pack
        run: dotnet pack -c Release --no-build -o packages /p:Version=${{ github.event.release.tag_name }} ./Cubido.Templates.csproj
      # https://learn.microsoft.com/en-us/nuget/nuget-org/trusted-publishing
      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Publish NuGet
        run: |
          for file in packages/*.nupkg; do
            dotnet nuget push "$file" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
          done
